###

GET http://localhost:8080/posts

###

POST http://localhost:8080/posts 
Content-Type: application/json

{
"title": "Hello", "sender": "Kevin", "content": "Hello World..."
}

###

GET http://localhost:8080/posts/673b418c7a4c7c28093f2633

###

PUT http://localhost:8080/posts/673b418c7a4c7c28093f2633
Content-Type: application/json

{
"title": "HelloOOOOOOOOOO", "sender": "GUY ATTIAS", "content": "GUY IS THE KING"
}

###