###

GET http://localhost:8080/posts

###

GET http://localhost:8080/posts?sender=Kevin

###

POST http://localhost:8080/posts 
Content-Type: application/json

{
"title": "Hello", "sender": "Kevin", "content": "Hello World..."
}

###

GET http://localhost:8080/posts/673b418c7a4c7c28093f2633

###

PUT http://localhost:8080/posts/673b418c7a4c7c28093f2633
Content-Type: application/json

{
"title": "HelloOOOOOOOOOO", "sender": "GUY ATTIAS", "content": "GUY IS THE KING"
}

###

DELETE  http://localhost:8080/comments/673ca8547843cfb55725c80f

###

GET   http://localhost:8080/comments/post/673b418c7a4c7c28093f2633

###

POST http://localhost:8080/comments 
Content-Type: application/json

{
"postID": "673b418c7a4c7c28093f2633", "sender": "Kevin", "content": "Hello World..."
}

###

PUT http://localhost:8080/comments/674067d4a1718b4a54d307b8
Content-Type: application/json

{
 "sender": "IDO", "content": "IDO IS THE GOAT"
}

